server:
  port: 8888

spring:
  application:
    name: user-web

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
    fetch-registry: true
    register-with-eureka: true
